## Docker Compose file, experimental and untested
# Run 'docker compose up' to start the service
version: '3'
services:
  web:
    build: .
    ports:
     - "8000:80"
    volumes:
     - ./data:/data
